Stardown-app/Stardown

- chromium/background.js
- chromium/content.js
- docs/develop.md
- firefox/background.js
- firefox/content.js
> Generalize messaging from background to content

- firefox/background.js
- firefox/content.js
- firefox/manifest.json
This PR makes the same changes as the previous one but for Firefox instead of Chromium.
> Add image copying support to the Firefox version

- README.md
- chromium/background.js
- chromium/manifest.json
- firefox/background.js
- firefox/manifest.json
> Show a notification when copying fails

- chromium/background.js
- chromium/content.js
- firefox/background.js
- firefox/content.js
> Add context menu option for videos

- chromium/background.js
- firefox/background.js
> Improve GitHub mp4 link rendering for GitHub

- chromium/background.js
- chromium/content.js
- firefox/background.js
- firefox/content.js
> Add a context menu option for audio

- chromium/background.js
- chromium/options.js
- firefox/background.js
- firefox/options.js
> Fix delay to click interval setting application

- src/content.js
> Fix rendering of Chrome YT videos in Obsidian

- rollup.config.firefox.mjs
- src/content.js
> Fix error "Clipboard write is not allowed"

- src/content.js
- src/md.js
- src/options.html
- src/options.js
> Prepare for use of the YouTube thumbnail service

- src/htmlSelection.js
> Fix selections that start above code & end within

- src/common.js
- src/content.js
- src/options.html
- src/options.js
- src/tableConverter.js
- src/tables.js
- test/jsonTables.js
> Change JSON output format to array of object

- chrome/config.js
- docs/troubleshooting.md
- firefox/config.js
- rollup.config.firefox.mjs
- src/background.js
- src/common.js
- src/content.js
- src/converters/README.md
- src/converters/json.js
- src/converters/md.js
- src/createTextFragmentArg.js
- src/generators/md.js
- src/htmlSelection.js
- src/options.html
- src/options.js
> Add markup language setting with markdown & HTML options

- chrome/config.js
- docs/develop.md
- firefox/config.js
- src/background.js
- src/content.js
- src/converters/README.md
- src/converters/md.js
- src/converters/mdAndHtml.js
- src/converters/utils/html.js
- src/converters/utils/urls.js
- src/htmlSelection.js
- src/options.html
> Add option to generate markdown with some HTML

- .github/workflows/release.yaml
The current error message is `Pattern 'stardown-$GITHUB_REF_NAME-firefox.zip' does not match any files.`
> Use echo to debug the action

- README.md
- src/sidebar.html
- src/sidebar.js
> Enforce notepad character and save time limits

- src/contentUtils.js
- src/getSetting.js
- src/settings.html
- src/settings.js
- src/sidebar.js
> Add setting to append or insert into notepad

- src/background.js
> Allow copy selection button to copy multiple tabs

- src/sidebar.js
See the new comment for an explanation.
> Replace some chars when saving notepad to sync

- README.md
- docs/manual-testing.md
- firefox/manifest.json
> Change default keyboard shortcuts for Firefox

- src/sidebar.js
> Show new byte limit immediately on change

- src/codejar.js
- src/codejar.ts
Closes #221. The bug only appeared in Firefox.
> Update CodeJar to commit 4d19174c5a2759a5bf90be26353f7c85715392fa

- src/htmlSelection.js
> Fix selection of tables that start with anchors
